"""add enable_image_resolution to settings

Revision ID: 99f59f8b6486
Revises: 004_add_template_style
Create Date: 2026-01-02 23:36:44.545046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f59f8b6486'
down_revision = '004_add_template_style'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('enable_image_resolution', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'enable_image_resolution')
    # ### end Alembic commands ###



